// src/archives/components/ChangePasswordPage.vue
<template>

<div id="ChangePasswordPage">
        <h1>Change Password</h1>
<app-user-detail :myName="name"></app-user-detail>
  <p>

     <input 
       type="text" 
       name="old_password" 
       v-model="input.old_password" 
       id="old_password" 
       placeholder="Current Password" 
     >
  
  </p>

  <p>
     <input 
       type="text" 
       name="new_password1" 
       v-model="input.new_password1" 
       id="new_password1" 
       placeholder="New Password" 
     >
  </p>

  <p>
     <input 
       type="text" 
       name="new_password2" 
       v-model="input.new_password2" 
       id="new_password2" 
       placeholder="New Password (again)" 
     >
  </p>

  <p>
    <input
      type="submit"
      value="CHANGE PASSWORD"
      v-on:click="change_password()"
    >
  </p> 

        
<p id=statusMessage>{{message}}</p>

</div>

</template>

<script>
var $ = require('jquery')
window.jQuery = $
export default {
	name: 'ChangePasswordPage',
        data () {
		return {
			profileSigninMessage: "",	
			message: "",
			username: "",
                	input: {
                    		old_password: "",
                    		new_password1: "",
                    		new_password2: "",
                    		new_password: ""
                	}
		}
	},

    // created: function () {
    created () {
    	this.scrollToTop(),
    	this.profileSigninMessage = this.$route.query.messageFromSigninPage
    	this.get_username();
    },

	methods: {
      		scrollToTop() {
      			window.scrollTo(0,0);
      		},

		async change_password(){

                	if(this.input.old_password != "" && this.input.new_password1 != "" && this.input.new_password2 != "") {
				if (this.input.new_password1 == this.input.new_password2) {
					this.input.new_password = this.input.new_password1;
		 			console.log("value of this.username");
		 			console.log(this.username);

		 			console.log("value of this.input.old_password");
		 			console.log(this.input.old_password);
		 			console.log("value of this.input.new_password");
		 			console.log(this.input.new_password);

					try{
						$.ajax({
							url: 'https://www.icanmakemyownapp.com/iqbal/v3/change-password.php',
                					type: 'POST',
                 					dataType: 'text',
		 					data: {username: this.username, old_password: this.input.old_password, new_password: this.input.new_password},
                 					success: (data, status, username, message) => {	// success funciton starts
								console.log("Value of data");
								console.log(data);


								if (data.trim() == "done")	{
									alert("Password Successfully Changed");
									console.log("Password Successfully Changed");
									var simpleString = "done" + ":" + this.username + ":" + this.input.new_password;
									// console.log ("value of simpleString");
									// console.log (simpleString);
									var encodedString = btoa(simpleString);
									this.$router.push({path: '/', query: {messageFromSigninPage:encodedString}});
								}
								// else if account not registered
								else {
									alert("Unable to register your account:" + data);
								}
                 					}	// success function ends
						});	// ajax call ends

					}catch(err){
						alert("inside catch err");
						alert(err);
						this.message = err;
					}
		
				}	// if password1 = password2 ends
				else {
					alert("Passwords do not match");
				}
		
                	} else {
                    		// console.log("A username and password must be present");
                    		alert("All fields are required");
                	}
		},	// function async register ends

	
    get_username(){
	try{
	var decodedString = atob(this.profileSigninMessage);
        let newArr = decodedString.split(":");

	console.log("Inside splitedList2")
	console.log(newArr[0])
	console.log(newArr[1])
	this.username = newArr[1]
	
	}
	catch(err){
		return "Error"
	}
    }	// function get_username ends
				

	}	// methods ends
}	// export default ends

</script>

<style scoped>
</style>

// src/account/ChangePasswordPage.tsx
/* eslint-disable no-unused-vars */
import React from 'react';

import SigninPage from './SigninPage';

// for formatting
import '../main_page/TopSectionMainPage/TopSectionMainPage.css';

import PropTypes from 'prop-types';

import $ from 'jquery';
declare var window : any;
window.$ = window.jQuery = $;

// window.jQuery = $;

class ChangePassword extends React.Component<any, any>  {

	static propTypes = {
		location: PropTypes.object.isRequired,
		history: PropTypes.object.isRequired
	}

	constructor(props: any) {
		super(props);
		this.state = {

			username: '',
			password: '',
			signinConfirmation: '',

			currentPassword: '',
			newPassword1: '',
			newPassword2: '',
			newPassword: '',
			errorMessage: ''

		};

		this.handleChangeCurrentPassword = this.handleChangeCurrentPassword.bind(this);
		this.handleChangeNewPassword1 = this.handleChangeNewPassword1.bind(this);
		this.handleChangeNewPassword2 = this.handleChangeNewPassword2.bind(this);

		this.handleSubmit = this.handleSubmit.bind(this);
	}


	// handlechange
	handleChangeCurrentPassword(event: any) {
		this.setState({ currentPassword: event.target.value });
	}

	handleChangeNewPassword1(event: any) {
		this.setState({ newPassword1: event.target.value });
	}

	handleChangeNewPassword2(event: any) {
		this.setState({ newPassword2: event.target.value });
	}

	onSubmitSignin = () => {

		this.props.history.push({
			pathname: 'SigninPage',
			state: { none: 'none' }
		});

	}

	// handleSubmit
	handleSubmit(event: any) {
		event.preventDefault();
		if (this.state.currentPassword !== '' && this.state.newPassword1 !== '' && this.state.newPassword2 !== '') {
			if (this.state.newPassword1.trim() === this.state.newPassword2.trim()) {
				this.setState({ newPassword: this.state.newPassword1 });
				try {
					$.ajax({
						url: 'https://www.icanmakemyownapp.com/iqbal/v3/change-password.php',
						type: 'POST',
						dataType: 'text',
						data: { username: this.state.username, old_password: this.state.currentPassword, new_password: this.state.newPassword },
						success: (data) => {	// success funciton starts
							if (data.trim() === 'done') {
								alert('Password Successfully Changed');
								this.setState({ errorMessage: 'Password Successfully Changed' });
								this.setState({ signinConfirmation: data });

								this.props.history.push({
									pathname: '/',
									state: { profileUsername: this.state.username, profilePassword: this.state.newPassword, profileSigninConfirmation: this.state.signinConfirmation }
								});

							}	// if data is equal to done ends
							else {
								alert('Unable to register your account:' + data);
								this.setState({ errorMessage: 'Unable to register your account:' + data });
							}
						}	// success function ends
					});	// ajax call ends

				}	// try ends
				catch (err) {
					alert('inside catch err');
					alert(err);
					this.setState({ errorMessage: err });
				}	// catch finishes
			}	// if passwords are same ends
			else {	// passwords are not same

				alert('Passwords do not match');
				this.setState({ errorMessage: 'Passwords do not match' });

			}	// if email not empty ends
		}	// if fields  are not empty ends

		else {
			alert('All fields are required');
			this.setState({ errorMessage: 'All fields are required' });
		}
	}

	componentDidMount() {
		window.scrollTo(0, 0);
		// retrive the data
		try {
			this.setState({ signinConfirmation: this.props.location.state.profileSigninConfirmation });
			this.setState({ username: this.props.location.state.profileUsername });
			this.setState({ password: this.props.location.state.profilePassword });
		}

		catch (e) {

			this.setState({ signinConfirmation: 'not signed in' });
			this.setState({ username: '' });
		}
	}


	render() {
		return (
			<div className="text-center">
				<h1>CHANGE PASSWORD</h1>
				<form onSubmit={this.handleSubmit}>

					<label>
						Current Password:
						<input type="text" value={this.state.currentPassword} onChange={this.handleChangeCurrentPassword} />
					</label>
					<p></p>

					<label>
						New Password:
						<input type="text" value={this.state.newPassword1} onChange={this.handleChangeNewPassword1} />
					</label>
					<p></p>

					<label>
						New Password(again):
						<input type="text" value={this.state.newPassword2} onChange={this.handleChangeNewPassword2} />
					</label>
					<p></p>

					<input type="submit" value="CHANGE PASSWORD!" />
				</form>
				<p onClick={() => this.onSubmitSignin()}>

					Already Registered?{'\n'}
					Login Here

				</p>

				<p>
					{this.state.errorMessage}
				</p>
			</div>
		);	// return ends
	}	// render function ends
}	// class ends

export default ChangePassword;
