// src/archives/components/ForgotPasswordPage.vue
<template>

<div id="ForgotPasswordPage">
        <h1>Forgot Password</h1>
<!-- <app-user-detail :myName="name"></app-user-detail> -->
  <p>

     <input 
       type="text" 
       name="email" 
       v-model="input.email" 
       id="email" 
       placeholder="Email" 
     >
  
  </p>


  <p>
    <input
      type="submit"
      value="REST MY PASSWORD!"
      v-on:click="reset_password()"
    >
  </p> 

        
<p id=statusMessage>{{message}}</p>

</div>

</template>

<!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"> -->

<script>
var $ = require('jquery')
window.jQuery = $
export default {
	name: 'ForgotPasswordPage',
        data () {
		return {
			message: "",
                	input: {
                    		email: ""
                	},
		}
	},

    created: function () {
    	this.scrollToTop()
    },

	methods: {
      		scrollToTop() {
      			window.scrollTo(0,0);
      		},

async reset_password () {
	console.log("Value of this.input.email.trim()");
	console.log(this.input.email.trim());
	
        if(this.input.email.trim() != "") {
	try{
		$.ajax({
			url: 'https://www.icanmakemyownapp.com/iqbal/v3/forgot-password.php',
                	type: 'POST',
                 	dataType: 'text',
		 	data: {email: this.input.email},
                 	success: (data) => {	// success funciton starts
				console.log("Value of this.input.email");
				console.log(this.input.email);
				console.log("data");
				console.log(data);
				if (data.trim() == "email sent")	{
					$("#statusMessage").text("Email sent.");
					console.log(data);
					alert("Email sent with the new password. Please check your email.");
					 this.$router.push({path: '/signinpage'});

				}
				else if (data.trim() == "email not found"){
					$("#statusMessage").text("Unable to find your email."); 
					alert("Could not found email in our system, please double check email address or create a new account.");
				}
                 	}	// success function ends
		});	// ajax call ends

	}catch(err){
		alert("inside catch err");
		alert(err);
		this.message = err;
	}
	}	// if email not empty ends
	else {
		console.log("Email can not be empty");
		alert("Email can not be empty");
		$("#statusMessage").text("Email can not be empty"); 
	}
}	// reset_password function ends
}	// methods ends
}	// export default ends

</script>

<style scoped>
</style>

// src/account/ForgotPasswordPage.tsx
/* eslint-disable no-unused-vars */
import React from 'react';

import SigninPage from './SigninPage';
import PropTypes from 'prop-types';

import $ from 'jquery';
declare var window : any;
window.$ = window.jQuery = $;

// window.jQuery = $;

class ForgotPassword extends React.Component<any, any> {

	static propTypes = {
		location: PropTypes.object.isRequired,
		history: PropTypes.object.isRequired
	}

	constructor(props: any) {
		super(props);
		this.state = {

			email: '',
			errorMessage: ''

		};

		this.handleChangeEmail = this.handleChangeEmail.bind(this);

		this.handleSubmit = this.handleSubmit.bind(this);
	}


	// handlechange
	handleChangeEmail(event: any) {
		this.setState({ email: event.target.value });
	}

	onSubmitSignin = () => {
		this.props.history.push({
			pathname: 'SigninPage',
			state: { none: 'none' }
		});
	}

	// handleSubmit
	handleSubmit(event: any) {

		if (this.state.email.trim() !== '') {
			try {
				$.ajax({
					url: 'https://www.icanmakemyownapp.com/iqbal/v3/forgot-password.php',
					type: 'POST',
					dataType: 'text',
					data: { email: this.state.email },
					success: (data) => {	// success funciton starts
						if (data.trim() === 'email sent') {
							alert('Email sent with the new password. Please check your email.');
							this.setState({ errorMessage: 'Email sent with the new password. Please check your email.' });

							this.props.history.push({
								pathname: 'SigninPage',
								state: { none: 'none' }
							});	// this.props.history.push ends

						}	// if data.trim == email sent ends
						else if (data.trim() === 'email not found') {
							alert('Could not found email in our system, please double check email address or create a new account.');
							this.setState({ errorMessage: 'Could not found email in our system, please double check email address or create a new account.' });
						}	// elese if ends
					}	// success function ends
				});	// ajax call ends

			}
			catch (err) {
				alert('inside catch err');
				alert(err);
				this.setState({ errorMessage: err });
			}	// catch ends
		}	// if email not empty ends
		else {
			alert('Email can not be empty');
			this.setState({ errorMessage: 'Email can not be empty' });
		}
		event.preventDefault();
	}
	componentDidMount() {
		window.scrollTo(0, 0);
	}

	render() {
		return (
			<div className="text-center">
				<h1>FORGOT PASSWORD</h1>
				<form onSubmit={this.handleSubmit}>
					<label>
						Email:
						<input type="text" value={this.state.email} onChange={this.handleChangeEmail} />
					</label>
					<p></p>
					<input type="submit" value="RESET MY PASSWORD!" />
				</form>
				<p onClick={() => this.onSubmitSignin()}>
					Already Registered?{'\n'}
					Login Here
				</p>
				<p>
					{this.state.errorMessage}
				</p>
			</div>
		);	// return ends
	}	// render ends
}	// class ends

export default ForgotPassword;
